# Feature options - Use _BUILD_ARG_ prefixed variables from devcontainer feature system
echo "Debug: _BUILD_ARG_VERSION = '$_BUILD_ARG_VERSION'"
echo "Debug: VERSION = '$VERSION'"
echo "Debug: _BUILD_ARG_INSTALLMAVEN = '$_BUILD_ARG_INSTALLMAVEN'"
echo "Debug: INSTALLMAVEN = '$INSTALLMAVEN'"
echo "Debug: _BUILD_ARG_INSTALLGRADLE = '$_BUILD_ARG_INSTALLGRADLE'"
echo "Debug: INSTALLGRADLE = '$INSTALLGRADLE'"
echo "Debug: _BUILD_ARG_JDKDISTRO = '$_BUILD_ARG_JDKDISTRO'"
echo "Debug: JDKDISTRO = '$JDKDISTRO'"
echo "Debug: JAVA_VERSION = '$_JAVA_VERSION'"
